/**
 * Build script for doc-to-slide-addon
 * 
 * Converts docs/03_user_guide.md to src/HelpSidebar.html
 * This ensures Single Source of Truth for documentation.
 */

const fs = require('fs');
const path = require('path');

const DOCS_DIR = path.join(__dirname, '..', '..', '..', 'docs');
const SRC_DIR = path.join(__dirname, '..', 'src');
const SOURCE_FILE = path.join(DOCS_DIR, '03_user_guide.md');
const OUTPUT_FILE = path.join(SRC_DIR, 'HelpSidebar.html');

/**
 * Simple Markdown to HTML converter
 * Handles: headers, lists, bold, code, blockquotes, links, hr
 */
function markdownToHtml(markdown) {
    let html = markdown;

    // Escape HTML entities first (except for our conversions)
    // html = html.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

    // Headers (h1-h3)
    html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
    html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
    html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');

    // Horizontal rule
    html = html.replace(/^---+$/gm, '<hr>');

    // Bold
    html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');

    // Inline code
    html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

    // Links
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank">$1</a>');

    // Blockquotes
    html = html.replace(/^> (.+)$/gm, '<blockquote><p>$1</p></blockquote>');

    // Unordered lists (handle nested with -)
    html = html.replace(/^-   (.+)$/gm, '<li>$1</li>');
    html = html.replace(/^- (.+)$/gm, '<li>$1</li>');

    // Ordered lists
    html = html.replace(/^\d+\.\s+(.+)$/gm, '<li>$1</li>');

    // Wrap consecutive <li> in <ul> or <ol>
    // This is a simplified approach - wrap all <li> blocks
    const lines = html.split('\n');
    const result = [];
    let inList = false;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const isListItem = line.trim().startsWith('<li>');

        if (isListItem && !inList) {
            result.push('<ul>');
            inList = true;
        } else if (!isListItem && inList) {
            result.push('</ul>');
            inList = false;
        }

        // Convert paragraphs (non-empty lines that aren't already HTML)
        if (!isListItem && line.trim() &&
            !line.trim().startsWith('<') &&
            !line.trim().startsWith('>')) {
            result.push(`<p>${line}</p>`);
        } else {
            result.push(line);
        }
    }

    if (inList) {
        result.push('</ul>');
    }

    return result.join('\n');
}

/**
 * Generate the full HTML file with styles
 */
function generateHelpSidebar(markdownContent) {
    const bodyContent = markdownToHtml(markdownContent);

    return `<!--
  ==============================================================================
  HelpSidebar.html - AUTO-GENERATED FILE
  ==============================================================================
  ⚠️ DO NOT EDIT THIS FILE DIRECTLY!
  
  This file is automatically generated from: docs/03_user_guide.md
  To update the help content, edit the source markdown file and run:
    npm run build
  ==============================================================================
-->
<!DOCTYPE html>
<html>

<head>
    <base target="_top">
    <link rel="stylesheet" href="https://ssl.gstatic.com/docs/script/css/add-ons1.css">
    <style>
        body {
            padding: 12px;
            font-family: 'Google Sans', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
        }

        h1, h2, h3 {
            margin-top: 24px;
            margin-bottom: 12px;
            font-weight: 500;
            color: #202124;
        }

        h1 {
            font-size: 24px;
            border-bottom: 2px solid #aaa;
            padding-bottom: 8px;
        }

        h2 {
            font-size: 18px;
            border-bottom: 1px solid #eee;
            padding-bottom: 6px;
        }

        h3 {
            font-size: 16px;
            font-weight: 600;
            color: #555;
        }

        p {
            margin-bottom: 16px;
        }

        ul, ol {
            margin-bottom: 16px;
            padding-left: 24px;
        }

        li {
            margin-bottom: 8px;
        }

        code {
            background-color: #f1f3f4;
            padding: 2px 4px;
            border-radius: 4px;
            font-family: 'Roboto Mono', monospace;
            font-size: 0.9em;
            color: #d93025;
        }

        blockquote {
            background-color: #e8f0fe;
            border-left: 4px solid #4285f4;
            margin: 0 0 16px 0;
            padding: 12px;
            border-radius: 4px;
            font-size: 0.9em;
        }

        hr {
            border: none;
            border-top: 1px solid #dadce0;
            margin: 24px 0;
        }

        a {
            color: #1a73e8;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }

        .header-logo {
            font-size: 32px;
            margin-bottom: 10px;
            display: block;
            text-align: center;
        }
    </style>
</head>

<body>
    <span class="header-logo">🤖📄➡️🎨</span>
${bodyContent}
</body>

</html>
`;
}

// Main execution
function main() {
    console.log('📄 Building HelpSidebar.html from docs/03_user_guide.md...');

    if (!fs.existsSync(SOURCE_FILE)) {
        console.error(`❌ Source file not found: ${SOURCE_FILE}`);
        process.exit(1);
    }

    const markdown = fs.readFileSync(SOURCE_FILE, 'utf-8');
    const html = generateHelpSidebar(markdown);

    fs.writeFileSync(OUTPUT_FILE, html, 'utf-8');
    console.log(`✅ Generated: ${OUTPUT_FILE}`);
}

main();
